//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elma.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EmptyState {
            get {
                object obj = ResourceManager.GetObject("EmptyState", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm Up
        ///Flat Track
        ///Twin Peaks
        ///Over and Under
        ///Uphill Battle
        ///Long Haul
        ///Hi Flyer
        ///Tag
        ///Tunnel Terror
        ///The Steppes
        ///Gravity Ride
        ///Islands in the Sky
        ///Hill Legend
        ///Loop-de-Loop
        ///Serpents Tale
        ///New Wave
        ///Labyrinth
        ///Spiral
        ///Turnaround
        ///Upside Down
        ///Hangman
        ///Slalom
        ///Quick Round
        ///Ramp Frenzy
        ///Precarious
        ///Circuitous
        ///Shelf Life
        ///Bounce Back
        ///Headbanger
        ///Pipe
        ///Animal Farm
        ///Steep Corner
        ///Zig-Zag
        ///Bumpy Journey
        ///Labyrinth Pro
        ///Fruit in the Den
        ///Jaws
        ///Curvaceous
        ///Haircut
        ///Double Trouble
        ///Framework
        ///Enduro
        ///He He
        ///F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LevelNames {
            get {
                return ResourceManager.GetString("LevelNames", resourceCulture);
            }
        }
    }
}
